// 프로젝트 구조 분석 스크립트

console.log("=== HostLab2 프로젝트 구조 분석 ===\n")

// 1. App Router 페이지 구조 분석
console.log("📁 App Router 페이지 구조:")
console.log("├── app/")
console.log("│   ├── page.tsx                    // 메인 홈페이지")
console.log("│   ├── layout.tsx                  // 전체 레이아웃")
console.log("│   ├── globals.css                 // 전역 스타일")
console.log("│   │")
console.log("│   ├── login/")
console.log("│   │   └── page.tsx               // 로그인 페이지")
console.log("│   │")
console.log("│   ├── signup/")
console.log("│   │   └── page.tsx               // 회원가입 페이지")
console.log("│   │")
console.log("│   ├── search/")
console.log("│   │   ├── page.tsx               // 검색 페이지")
console.log("│   │   ├── loading.tsx            // 검색 로딩")
console.log("│   │   └── results/")
console.log("│   │       ├── page.tsx           // 검색 결과 페이지")
console.log("│   │       └── loading.tsx        // 검색 결과 로딩")
console.log("│   │")
console.log("│   ├── analysis/")
console.log("│   │   ├── page.tsx               // 분석 페이지")
console.log("│   │   └── loading.tsx            // 분석 로딩")
console.log("│   │")
console.log("│   ├── accommodation/")
console.log("│   │   ├── page.tsx               // 🎯 지역 숙소 확인 페이지 (콤보박스 이슈가 있던 곳)")
console.log("│   │   └── loading.tsx            // 숙소 로딩")
console.log("│   │")
console.log("│   ├── region-data/")
console.log("│   │   ├── page.tsx               // 지역 데이터 페이지")
console.log("│   │   └── loading.tsx            // 지역 데이터 로딩")
console.log("│   │")
console.log("│   ├── region-properties/")
console.log("│   │   ├── page.tsx               // 지역 부동산 페이지")
console.log("│   │   └── loading.tsx            // 지역 부동산 로딩")
console.log("│   │")
console.log("│   ├── investment-tools/")
console.log("│   │   └── page.tsx               // 투자 도구 페이지")
console.log("│   │")
console.log("│   ├── host-simulation/")
console.log("│   │   ├── page.tsx               // 호스트 시뮬레이션 페이지")
console.log("│   │   └── [id]/")
console.log("│   │       └── page.tsx           // 개별 시뮬레이션 페이지")
console.log("│   │")
console.log("│   ├── consultation/")
console.log("│   │   └── page.tsx               // 상담 페이지")
console.log("│   │")
console.log("│   ├── saved-results/")
console.log("│   │   ├── page.tsx               // 저장된 결과 목록")
console.log("│   │   └── [id]/")
console.log("│   │       ├── page.tsx           // 개별 저장 결과")
console.log("│   │       ├── page-with-password.tsx // 비밀번호 보호 결과")
console.log("│   │       └── loading.tsx        // 저장 결과 로딩")
console.log("│   │")
console.log("│   └── admin/")
console.log("│       ├── page.tsx               // 관리자 메인")
console.log("│       ├── user-permissions/")
console.log("│       │   └── page.tsx           // 사용자 권한 관리")
console.log("│       ├── assign-users/")
console.log("│       │   └── page.tsx           // 사용자 할당")
console.log("│       └── consultation-notes/")
console.log("│           └── page.tsx           // 상담 노트 관리")

console.log("\n")

// 2. API Routes 분석
console.log("🔌 API Routes:")
console.log("├── app/api/")
console.log("│   ├── fetch-data/route.ts         // 데이터 크롤링")
console.log("│   ├── search/route.ts             // 검색 API")
console.log("│   ├── regions/route.ts            // 지역 정보 API")
console.log("│   ├── db-regions/route.ts         // DB 지역 정보")
console.log("│   ├── admin-regions/route.ts      // 관리자 지역 API")
console.log("│   ├── save-region/route.ts        // 지역 저장")
console.log("│   ├── save-analysis/route.ts      // 분석 결과 저장")
console.log("│   ├── save-hierarchical-data/route.ts // 계층 데이터 저장")
console.log("│   ├── bulk-save-regional-data/route.ts // 대량 지역 데이터 저장")
console.log("│   ├── update-occupancy/route.ts   // 점유율 업데이트")
console.log("│   ├── update-rental-costs/route.ts // 임대 비용 업데이트")
console.log("│   ├── naver-property/route.ts     // 네이버 부동산 API")
console.log("│   ├── hierarchical-data/route.ts  // 계층 데이터 API")
console.log("│   ├── user-permissions/route.ts   // 사용자 권한 API")
console.log("│   ├── analyze-summary/route.ts    // AI 분석 요약")
console.log("│   ├── signup/route.ts             // 회원가입 API")
console.log("│   └── create-consultation-table/route.ts // 상담 테이블 생성")

console.log("\n")

// 3. 주요 컴포넌트 분석
console.log("🧩 주요 컴포넌트:")
console.log("├── components/")
console.log("│   ├── nav-bar.tsx                 // 네비게이션 바")
console.log("│   ├── search-form.tsx             // 검색 폼")
console.log("│   ├── search-results.tsx          // 검색 결과")
console.log("│   ├── property-card.tsx           // 부동산 카드")
console.log("│   ├── property-list-simple.tsx    // 간단한 부동산 리스트")
console.log("│   ├── property-detail.tsx         // 부동산 상세")
console.log("│   │")
console.log("│   ├── 📊 분석 관련:")
console.log("│   ├── market-analysis.tsx         // 시장 분석")
console.log("│   ├── price-analysis.tsx          // 가격 분석")
console.log("│   ├── occupancy-analysis.tsx      // 점유율 분석")
console.log("│   ├── compare-time-analysis.tsx   // 시간 비교 분석")
console.log("│   ├── compare-area-analysis.tsx   // 지역 비교 분석")
console.log("│   ├── custom-profit-analysis.tsx  // 맞춤 수익 분석")
console.log("│   ├── ai-analysis-summary.tsx     // AI 분석 요약")
console.log("│   │")
console.log("│   ├── 🗺️ 지도 관련:")
console.log("│   ├── map-wrapper.tsx             // 지도 래퍼")
console.log("│   ├── client-map-component.tsx    // 클라이언트 지도")
console.log("│   ├── map-client-component.tsx    // 🎯 지도 클라이언트 (accommodation 페이지용)")
console.log("│   │")
console.log("│   ├── 💰 투자/수익 관련:")
console.log("│   ├── budget-settings.tsx         // 예산 설정")
console.log("│   ├── location-investment-score.tsx // 위치 투자 점수")
console.log("│   ├── upgrade-roi-calculator.tsx  // ROI 계산기")
console.log("│   ├── host-simulation.tsx         // 호스트 시뮬레이션")
console.log("│   │")
console.log("│   ├── 📋 데이터 관리:")
console.log("│   ├── file-uploader.tsx           // 파일 업로더")
console.log("│   ├── file-uploader-fixed.tsx     // 수정된 파일 업로더")
console.log("│   ├── hierarchical-data-uploader.tsx // 계층 데이터 업로더")
console.log("│   ├── region-data-save-modal.tsx  // 지역 데이터 저장 모달")
console.log("│   ├── simplified-region-save-modal.tsx // 간단한 지역 저장 모달")
console.log("│   ├── region-data-preview.tsx     // 지역 데이터 미리보기")
console.log("│   │")
console.log("│   └── 🔧 기타:")
console.log("│       ├── consultation-notes.tsx  // 상담 노트")
console.log("│       ├── save-results-button.tsx // 결과 저장 버튼")
console.log("│       ├── delete-result-button.tsx // 결과 삭제 버튼")
console.log("│       ├── pdf-export-button.tsx   // PDF 내보내기")
console.log("│       └── password-protection.tsx // 비밀번호 보호")

console.log("\n")

// 4. 현재 이슈 분석
console.log("🚨 현재 확인된 이슈:")
console.log("1. accommodation/page.tsx - 콤보박스가 지도에 가려지는 문제 (해결됨)")
console.log("2. 사용자가 요청한 페이지를 정확히 찾지 못하는 문제")
console.log("3. 중복된 컴포넌트들 존재 (map-client-component.tsx vs client-map-component.tsx)")
console.log("4. 파일 업로더 중복 (file-uploader.tsx vs file-uploader-fixed.tsx)")

console.log("\n=== 분석 완료 ===")
